# Generated by Django 4.2.3 on 2023-07-14 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField()),
                ('comment', models.TextField()),
                ('like_number', models.IntegerField(default=0)),
                ('like_order', models.IntegerField(default=0, verbose_name='인기수')),
                ('recommendation_order', models.DateTimeField(auto_now_add=True, verbose_name='최신수')),
                ('human_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.humaninformation')),
            ],
            options={
                'ordering': ['-like_order'],
            },
        ),
    ]
