# Generated by Django 4.2.3 on 2023-07-14 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HumanDrugInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('office_name', models.CharField(max_length=255)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HumanInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humanId', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HumanPharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('business_hours', models.CharField(max_length=255)),
                ('drug_stock', models.IntegerField()),
                ('office_number', models.IntegerField()),
                ('reservation_number', models.IntegerField()),
                ('pharmacist_information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='social.humaninformation')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.IntegerField()),
                ('advice_number', models.IntegerField()),
                ('book_mark', models.BooleanField()),
                ('reservation_available', models.BooleanField()),
                ('advice_available', models.BooleanField()),
                ('office_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='social.humanpharmacy')),
            ],
        ),
    ]
